
import os
import sys
import json
import hashlib
import time

# Add project root to path
sys.path.append(os.getcwd())

from src.models.hf_client import HFClient

# Critical Determinants for Demo
DEMO_SEQUENCES = {
    "NDM-1": "MELPNIMHPVAKLSTALAAALMLSGCMPGEIRPTIGQQMETGDQRFGDLVFRQLAPNVWQHTSYLDMPGFGAVASNGLIVRDGGRVLVVDTAWTDDQTAQILNWIKQEINLPVALAVVTHAHQDKMGGMDALHAAGIATYANALSNQLAPQEGMVAAQHSLTFAANGWVEPATAPNFGPLKVFYPGPGHTSDNITVGIDGTDIAFGGCLIKDSKAKSLGNLGDADTEHYAASARAFGAAFPKASMIVMSHSAPDSRAAITHTARMADKLR",
    "KPC-2": "MSLYRRLVLLSCLSWPLAGFSATALTNLVAEPFAKLEQDFGGSIGVYAMDTGSGATVSYRAEERFPLCSSFKGFLAAAVLERSQQAGVDVAYLEKKATGVNAERIGASRPTDTPFGWKTGRRGMAAVRQASVTVYPPEAPTGRTVVLTDDMGDQQVDFLRENSNVVLAVAGGIDGKRLSIAQALWCPPYIGLATGGGSSAKDEEELASIQKRGLLDLALPGCPRRPTEEVKIEIVPAAEKQAAVAIGGLIAQGLKAGPLGLWVDGTPTGQG",
    "mecA": "MRINDYIINQIIKFFLSSIKDSKIVRKVQNKIPNKIVYKKSTFGGIGIGIAIYIIGIIYLIVLYKIKNKDIFPKPIEKIKKEFSDNKKIFIIDDSLDKEQVEKIQNDKEKIKFPNNIDQIMKMKGQKEIVNKLAIEFTEPKIPKIAVLLKDTNSDNKQLKDIIGIPKEIDLIIKKEKILNKKEIKKIKDITNQLKRKILEKEIKTEKIKEIGANKVQLIAGLIDNLKDIKDRKILEKILNEIKNELK",
    "vanA": "MNRIVFVCGNGGFVGRHMLDRILQDEQGLDVKVVAIDTDSRELAEQAKKQGVKIQVRDLAGSDAGLYDAIKAGGVQVIGYCGAGFVPSEEMAKQYAVRAQDLGILVDTAQMPMITEVAQGKLIVVGAGLTMDDVARHLHPTQIVSAHKSYMHGQKKRK",
    "MexB": "MRSLLLLLAFVLVAGVSAQADDLNAQVGVIDTSRAITLADKEAIGLDRQVFLTGTPVRLTDLRLTDKQGNHLVITGNPVNAQGQLQVLDGKLVLGQPLTGTPVRLADLRLTDKQGNHLVITGNPVNAQGQLQVLDGKLVLGQPL"
}

def precompute():
    client = HFClient()
    print("Precomputing Synthetic Embeddings (Offline Mode)...")
    
    cache_dir = "data/cache/embeddings"
    os.makedirs(cache_dir, exist_ok=True)

    for name, seq in DEMO_SEQUENCES.items():
        print(f"Processing {name}...")
        # Client now handles caching and synthetic generation
        vec = client.get_embedding(seq)
        if vec:
            print(f"  [OK] {name} cached. Length: {len(vec)}")
            # Also save by name for easier debugging/loading if needed
            with open(os.path.join(cache_dir, f"{name}.json"), "w") as f:
                json.dump({"determinant": name, "embedding": vec}, f)
        else:
            print(f"  [FAIL] {name}")

    print("\nPrecomputation Complete.")

if __name__ == "__main__":
    precompute()
